name: 'user-web'
port: 8021

user_srv:
  host: '192.168.0.103'
  port: 50051
  name: 'user-srv'

jwt:
  key: '12345'

redis:
  host: '192.168.0.50'
  port: 6379

consul:
  host: '192.168.0.50'
  port: 8500